# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TagLifeApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='vote',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
