# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 19:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TagLifeApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taglifeuser',
            name='user',
        ),
        migrations.DeleteModel(
            name='TagLifeUser',
        ),
    ]
