# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TagLifeApp', '0002_auto_20161203_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='vote',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
