# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 19:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TagLifeApp', '0003_auto_20161203_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predicate',
            name='user',
        ),
        migrations.AlterField(
            model_name='entrytagrelation',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations', to='TagLifeApp.Entry'),
        ),
        migrations.AlterField(
            model_name='entrytagrelation',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatedEntries', to='TagLifeApp.Tag'),
        ),
        migrations.AlterField(
            model_name='followtopicrelation',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='TagLifeApp.Topic'),
        ),
        migrations.AlterField(
            model_name='followtopicrelation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='topictagrelation',
            name='predicate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations', to='TagLifeApp.Predicate'),
        ),
        migrations.AlterField(
            model_name='topictagrelation',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations', to='TagLifeApp.Tag'),
        ),
        migrations.AlterField(
            model_name='topictagrelation',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations', to='TagLifeApp.Topic'),
        ),
    ]
